name: CI/CD Deploy to GCP

on:
  push:
    branches:
      - main

env:
  REGION: asia-southeast2    # ganti sesuai region Artifact Registry kamu
  REPO_NAME: mercari-repo    # ganti sesuai nama repo Artifact Registry

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker to use Artifact Registry
      run: |
        gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

    # Build & Push Auth Service
    - name: Build & Push auth-service image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 \
          -t ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/auth-service:latest \
          ./auth-service --push

    # Build & Push Cart Service
    - name: Build & Push cart image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 \
          -t ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/cart:latest \
          ./cart --push

    # Build & Push Product Service
    - name: Build & Push product image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 \
          -t ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/product:latest \
          ./product --push

    # Build & Push Gateway Service
    - name: Build & Push gateway-service image
      run: |
        docker buildx build --platform linux/amd64,linux/arm64 \
          -t ${{ env.REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/${{ env.REPO_NAME }}/gateway-service:latest \
          ./gateway-service --push

    # SSH to VM and Deploy (pastikan docker-compose.yml sudah ada di VM)
    - name: Deploy on VM via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USER }}
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          cd ~/mercari         # atau ganti path sesuai lokasi project di VM
          docker-compose pull
          docker-compose up -d --remove-orphans
